require('modules.core.settings')
require('modules.core.mappings')
require('modules.core.colors')
require('modules.core.lualine')
require('modules.core.scratch')
require('modules.core.snip')
require('modules.core.lsp-installer')
