require('modules.core.settings')
require('modules.core.mappings')
-- require('modules.core.colors-rose-pine')
-- require('modules.core.colors-luna')
-- require('modules.core.colors-nord')
-- require('modules.core.colors.poimandres')
-- require('modules.core.colors.oxocarbon')
require('modules.core.colors.gruvboxbby')
require('modules.core.lualine')
require('modules.core.scratch')
require('modules.core.snip')
require('modules.core.lsp-installer')
require('modules.core.autocmd')
require('modules.core.usercmd')
