require('modules.core.autocmd.run')
require('modules.core.autocmd.conceal_norg')
require('modules.core.autocmd.format_save')
require('modules.core.autocmd.rell_ft')
require('modules.core.autocmd.rell_test')
require('modules.core.autocmd.markdown')
